
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00260F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF003E1C)
val onPrimaryContainerLight = Color(0xFF72AA7E)
val secondaryLight = Color(0xFF4E6451)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E9D1)
val onSecondaryContainerLight = Color(0xFF546A57)
val tertiaryLight = Color(0xFF071C4D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF213263)
val onTertiaryContainerLight = Color(0xFF8B9BD3)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FAF4)
val onBackgroundLight = Color(0xFF191C19)
val surfaceLight = Color(0xFFF8FAF4)
val onSurfaceLight = Color(0xFF191C19)
val surfaceVariantLight = Color(0xFFDCE5DA)
val onSurfaceVariantLight = Color(0xFF414941)
val outlineLight = Color(0xFF717970)
val outlineVariantLight = Color(0xFFC0C9BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312E)
val inverseOnSurfaceLight = Color(0xFFEFF1EC)
val inversePrimaryLight = Color(0xFF9AD4A5)
val surfaceDimLight = Color(0xFFD9DBD5)
val surfaceBrightLight = Color(0xFFF8FAF4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4EE)
val surfaceContainerLight = Color(0xFFEDEFE9)
val surfaceContainerHighLight = Color(0xFFE7E9E3)
val surfaceContainerHighestLight = Color(0xFFE1E3DD)

val primaryLightMediumContrast = Color(0xFF00260F)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF003E1C)
val onPrimaryContainerLightMediumContrast = Color(0xFF98D2A3)
val secondaryLightMediumContrast = Color(0xFF263B2A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5C725F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF071C4D)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF213263)
val onTertiaryContainerLightMediumContrast = Color(0xFFB2C2FD)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8FAF4)
val onBackgroundLightMediumContrast = Color(0xFF191C19)
val surfaceLightMediumContrast = Color(0xFFF8FAF4)
val onSurfaceLightMediumContrast = Color(0xFF0F120F)
val surfaceVariantLightMediumContrast = Color(0xFFDCE5DA)
val onSurfaceVariantLightMediumContrast = Color(0xFF303831)
val outlineLightMediumContrast = Color(0xFF4C554C)
val outlineVariantLightMediumContrast = Color(0xFF676F66)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E312E)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF1EC)
val inversePrimaryLightMediumContrast = Color(0xFF9AD4A5)
val surfaceDimLightMediumContrast = Color(0xFFC5C7C2)
val surfaceBrightLightMediumContrast = Color(0xFFF8FAF4)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F4EE)
val surfaceContainerLightMediumContrast = Color(0xFFE7E9E3)
val surfaceContainerHighLightMediumContrast = Color(0xFFDBDED8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD0D2CD)

val primaryLightHighContrast = Color(0xFF00260F)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF003E1C)
val onPrimaryContainerLightHighContrast = Color(0xFFD0FFD6)
val secondaryLightHighContrast = Color(0xFF1C3121)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF394E3D)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF071C4D)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF213263)
val onTertiaryContainerLightHighContrast = Color(0xFFF2F2FF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8FAF4)
val onBackgroundLightHighContrast = Color(0xFF191C19)
val surfaceLightHighContrast = Color(0xFFF8FAF4)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE5DA)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF262E27)
val outlineVariantLightHighContrast = Color(0xFF434B43)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E312E)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF9AD4A5)
val surfaceDimLightHighContrast = Color(0xFFB7B9B4)
val surfaceBrightLightHighContrast = Color(0xFFF8FAF4)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF1EC)
val surfaceContainerLightHighContrast = Color(0xFFE1E3DD)
val surfaceContainerHighLightHighContrast = Color(0xFFD3D5D0)
val surfaceContainerHighestLightHighContrast = Color(0xFFC5C7C2)

val primaryDark = Color(0xFF9AD4A5)
val onPrimaryDark = Color(0xFF003919)
val primaryContainerDark = Color(0xFF003E1C)
val onPrimaryContainerDark = Color(0xFF72AA7E)
val secondaryDark = Color(0xFFB5CDB6)
val onSecondaryDark = Color(0xFF213525)
val secondaryContainerDark = Color(0xFF374C3A)
val onSecondaryContainerDark = Color(0xFFA4BBA5)
val tertiaryDark = Color(0xFFB4C5FF)
val onTertiaryDark = Color(0xFF1C2E5E)
val tertiaryContainerDark = Color(0xFF213263)
val onTertiaryContainerDark = Color(0xFF8B9BD3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111411)
val onBackgroundDark = Color(0xFFE1E3DD)
val surfaceDark = Color(0xFF111411)
val onSurfaceDark = Color(0xFFE1E3DD)
val surfaceVariantDark = Color(0xFF414941)
val onSurfaceVariantDark = Color(0xFFC0C9BE)
val outlineDark = Color(0xFF8B9389)
val outlineVariantDark = Color(0xFF414941)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3DD)
val inverseOnSurfaceDark = Color(0xFF2E312E)
val inversePrimaryDark = Color(0xFF336942)
val surfaceDimDark = Color(0xFF111411)
val surfaceBrightDark = Color(0xFF373A36)
val surfaceContainerLowestDark = Color(0xFF0C0F0C)
val surfaceContainerLowDark = Color(0xFF191C19)
val surfaceContainerDark = Color(0xFF1D201D)
val surfaceContainerHighDark = Color(0xFF282B27)
val surfaceContainerHighestDark = Color(0xFF323632)

val primaryDarkMediumContrast = Color(0xFFAFEAB9)
val onPrimaryDarkMediumContrast = Color(0xFF002D12)
val primaryContainerDarkMediumContrast = Color(0xFF659D72)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCAE3CB)
val onSecondaryDarkMediumContrast = Color(0xFF162A1B)
val secondaryContainerDarkMediumContrast = Color(0xFF809682)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD3DBFF)
val onTertiaryDarkMediumContrast = Color(0xFF102253)
val tertiaryContainerDarkMediumContrast = Color(0xFF7F8FC6)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF111411)
val onBackgroundDarkMediumContrast = Color(0xFFE1E3DD)
val surfaceDarkMediumContrast = Color(0xFF111411)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF414941)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD6DFD4)
val outlineDarkMediumContrast = Color(0xFFACB4AA)
val outlineVariantDarkMediumContrast = Color(0xFF8A9389)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E3DD)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B27)
val inversePrimaryDarkMediumContrast = Color(0xFF1B522E)
val surfaceDimDarkMediumContrast = Color(0xFF111411)
val surfaceBrightDarkMediumContrast = Color(0xFF424541)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF060806)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E1B)
val surfaceContainerDarkMediumContrast = Color(0xFF252925)
val surfaceContainerHighDarkMediumContrast = Color(0xFF303330)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3E3B)

val primaryDarkHighContrast = Color(0xFFC2FECC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF96D0A1)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F04)
val secondaryDarkHighContrast = Color(0xFFDEF6DE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB1C9B2)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F04)
val tertiaryDarkHighContrast = Color(0xFFEEEFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB0C1FB)
val onTertiaryContainerDarkHighContrast = Color(0xFF000828)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF111411)
val onBackgroundDarkHighContrast = Color(0xFFE1E3DD)
val surfaceDarkHighContrast = Color(0xFF111411)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF414941)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEAF2E7)
val outlineVariantDarkHighContrast = Color(0xFFBCC5BB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E3DD)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF1B522E)
val surfaceDimDarkHighContrast = Color(0xFF111411)
val surfaceBrightDarkHighContrast = Color(0xFF4E514D)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D201D)
val surfaceContainerDarkHighContrast = Color(0xFF2E312E)
val surfaceContainerHighDarkHighContrast = Color(0xFF393C38)
val surfaceContainerHighestDarkHighContrast = Color(0xFF444844)



val freshColor = Color(0xFF44FF78)
val staleColor = Color(0xFFFF9E44)

val primaryColor
    @Composable
    get() = if (isSystemInDarkTheme()) Color(0xFF86A8FC)
    else Color(0xFF283556)

val headerColor
    @Composable
    get() = if (isSystemInDarkTheme()) Color(0xFF0C0C0C)
    else Color(0xFF283556)

val surfaceColor
    @Composable
    get() = if (isSystemInDarkTheme()) Color(0xFF161616)
    else Color(0xFFFFFFFF)

val textColor
    @Composable
    get() = if (isSystemInDarkTheme()) Color(0xFFFFFFFF)
    else Color(0xFF000000)


